{{- if .Values.debugPy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "abider.fullname" . }}
  labels:
    {{- include "abider.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: debugpy
      protocol: TCP
      name: debugpy
  selector:
    {{- include "abider.selectorLabels" . | nindent 4 }}
{{- end }}
