FROM docker.io/python:3.11.5-alpine
ARG ABIDER_WORK_DIR='/usr/src/app/'
WORKDIR ${ABIDER_WORK_DIR}
# install useful commands
RUN apk add curl --no-cache
COPY --chown=405:405 ./requirements-dev.txt .
RUN pip install --no-cache-dir --upgrade -r ./requirements-dev.txt
COPY --chown=405:405 ./ ./
USER 405
CMD ["python", "main.py"]
