name: Container Build
"on":
  workflow_dispatch: null
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
      - 'dev'
jobs:
  build_all:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Helm - Setup
        uses: azure/setup-helm@v3
      - name: GitHub - Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker - Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'amd64,arm64'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: GitHub - Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker - Metadata - Alpine
        id: alpine
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/daemondude23/abider/alpine
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=semver,pattern=v{{version}}
      - name: Docker = Metadata - Debian
        id: debian
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/daemondude23/abider/debian
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=semver,pattern=v{{version}}
      - name: Docker - Build and Push - Alpine
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.alpine.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          context: ./src/
          file: ./src/Dockerfile-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker - Build and Push - Debian
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.debian.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          context: ./src/
          file: ./src/Dockerfile-debian
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: GitHub - Create Release (Draft)
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm - Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: deploy/helm/charts/abider
          config: deploy/helm/charts/abider/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
